apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gfhg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gfhg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gfhg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gfhg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gfhg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xehf-tenant/rhtap-demo-app/hacbs-test-project-gfhg@sha256:c3b5209e6b7770e3737df5df9e7e9a392ee1499b5389b18d6f4f9b756ef05ad1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
